name: CreatePR

on:
  create:

jobs:
  create_pr:
    runs-on: ubuntu-latest
    
    continue-on-error: true

    outputs:
      email: ${{ steps.get-email.outputs.email }}
      failure: ${{ steps.failure_handling.outputs.failure }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 1

      - name: Open pull request
        id: open-pull-request
        if: ${{ ! startsWith(github.ref, 'refs/heads/rebased') }}
        run: |
          gh pr create \
            --title "Pull Request to create/update rebased branch for '${{ github.ref }}'" \
            --body "Programmatically created Pull Request to automatically keep merge branch to develop up-to-date" \
            --base develop \
            --head ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Get email
        id: get-email
        uses: evvanErb/get-github-email-by-username-action@v2.0
        with:
          github-username: ${{ github.event.sender.login }}
          token: ${{ secrets.GH_TOKEN }}
          
      - name: Failure handling
        if: failure()
        id: failure_handling
        run: |
            FAILURE=${{ true }}
            echo "failure=$FAILURE" >> $GITHUB_OUTPUT


  notification_success:

    needs: [create_pr]    
    if: ("${{ needs.create_pr.outputs.failure }}" != "true")
    
    uses: itext/rups/.github/workflows/sendslackmsgtopusher.yml@createRebased
    secrets: inherit
    with:
      emailslackuser: ${{ needs.create_pr.outputs.email }}
      shortmsg: "Pull request created for '${{ github.ref }}'!"
      blocks: [
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": "Pull request created for `${{ github.ref }}` in `${{ github.server_url }}/${{ github.repository }}`"
            }
        }
      ]

  notification_failure:

    needs: [create_pr]    
    if: ("${{ needs.create_pr.outputs.failure }}" == "true")
    
    uses: itext/rups/.github/workflows/sendslackmsgtopusher.yml@createRebased
    secrets: inherit
    with:
      emailslackuser: ${{ needs.create_pr.outputs.email }}
      shortmsg: "No pull request created for '${{ github.ref }}'!"
      blocks: [
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": ":alert-beam: No pull request created in `${{ github.server_url }}/${{ github.repository }}`:"
            }
        },
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": "Check if `${{ github.ref }}` has changes compared to `develop` & push again"
            }
        }
      ]


            
       
