name: LicenseCheck

on:
  push:
    # 'branches-ignore' or 'branches' can be used to filter specific branches.
    # By default, without any filters, it runs on every push to all branches.
    # To be explicit, you can use:
    branches-ignore:
      - 'develop'
      - 'master'
      - 'rebased/*'

jobs:
  build:
    runs-on: ubuntu-latest

    continue-on-error: true

    steps:
      - name: Fallback Slack notification
        id: fallback_slack
        uses: slackapi/slack-github-action@v2.1.1
        with:
          errors: true
          method: chat.postMessage # https://api.slack.com/methods/chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            "channel": "ci",
            "text": "This is a test",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":alert: *LICENSES DETECTED* :alert:"
                }
              }
            ]
