name: LicenseCheck

on:
  push:
    # 'branches-ignore' or 'branches' can be used to filter specific branches.
    # By default, without any filters, it runs on every push to all branches.
    # To be explicit, you can use:
    branches-ignore:
      - 'develop'
      - 'master'
      - 'rebased/*'

jobs:
  build:
    runs-on: ubuntu-latest

    continue-on-error: true

    steps:
      - name: Fallback Email notification
        id: fallback_mail
        uses: dawidd6/action-send-mail@v6
        with:
            # Required mail server address if not connection_url:
            server_address: smtp.gmail.com
            # Optional whether this connection use TLS (default is true if server_port is 465)
            secure: true
            # Required mail subject:
            subject: Github Actions job result
            # Required recipients' addresses:
            to: marco.andries@apryse.com
            # Required sender full name (address can be skipped):
            from: GitHub licenseCheck action # <user@example.com>
            # Optional plain body:
            body: licenseCheck failed, please check Actions logs!
            # Optional unsigned/invalid certificates allowance:
            ignore_cert: true
            # Optional priority: 'high', 'normal' (default) or 'low'
            priority: high
